
services:
  airflow-init:
    image: apache/airflow:2.9.1
    entrypoint: bash -c "mkdir -p /opt/airflow/logs && chown -R 50000:0 /opt/airflow/logs && mkdir -p /opt/airflow/data && chown -R 50000:0 /opt/airflow/data"
    user: "0:0"
    volumes:
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    networks:
      - airflow_network
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      WEBHOOK_DISCORD: ${WEBHOOK_DISCORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - airflow_network

  airflow-webserver:
    build: .
    depends_on:
      - postgres
      - redis
      - airflow-scheduler
      - airflow-worker
      - airflow-init
    environment:
      AIRFLOW__WEBSERVER__BASE_URL: https://airflow.dataflor.space
      AIRFLOW__WEBSERVER__WEB_SERVER_URL_PREFIX: /
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__FERNET_KEY: "${FERNET_KEY}"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      _PIP_ADDITIONAL_REQUIREMENTS: "-r /requirements.txt"
      WORKDIR_PATH: /opt/airflow
      WEBHOOK_DISCORD: ${WEBHOOK_DISCORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
  
    volumes:
      - ./dags:/opt/airflow/dags:ro
      - ./helpers:/opt/airflow/helpers:ro
      - ./scrappers:/opt/airflow/scrappers:ro
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./requirements.txt:/requirements.txt:ro
      - ./.env:/opt/airflow/.env:ro
    ports:
      - 8080:8080
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
      airflow webserver
      "
    networks:
      - airflow_network

  airflow-scheduler:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__FERNET_KEY: "${FERNET_KEY}"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      WORKDIR_PATH: /opt/airflow
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      WEBHOOK_DISCORD: ${WEBHOOK_DISCORD}
    
    volumes:
      - ./dags:/opt/airflow/dags:ro
      - ./helpers:/opt/airflow/helpers:ro
      - ./scrappers:/opt/airflow/scrappers:ro
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: airflow scheduler
    networks:
      - airflow_network

  airflow-worker:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__FERNET_KEY: "${FERNET_KEY}"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      WORKDIR_PATH: /opt/airflow
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      WEBHOOK_DISCORD: ${WEBHOOK_DISCORD}
    
    volumes:
      - ./dags:/opt/airflow/dags:ro
      - ./helpers:/opt/airflow/helpers:ro
      - ./scrappers:/opt/airflow/scrappers:ro
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: airflow celery worker
    networks:
      - airflow_network

networks:
  airflow_network:
    driver: bridge
